spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

  devtools:
    livereload:
        enabled: true

cloud:
  aws:
    s3:
      bucket: team4-unnies-static
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true