spring:
  profiles:
    active: development

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
    session:
      tracking-modes: cookie

  devtools:
    livereload:
      enabled: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  config: classpath:logback-${spring.profiles.active}.xml

cloud:
  aws:
    s3:
      bucket: team4-unnies-static
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true
      accessKey: ${AWS_S3_ACCESS_KEY}
      secretKey: ${AWS_S3_SECRET_KEY}

handlebars:
  cache: false
  suffix: .html
  expose-session-attributes: true

---

spring:
  profiles: development
  datasource:
    data: classpath:import.sql
    url: jdbc:mysql://localhost:3306/baemin-nanumchan?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: unnies
    password: unnies
  flyway:
    enabled: false

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    properties.hibernate:
      hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor

logging:
  level:
    org.hibernate:
    - debug
    - type.descriptor.sql.BasicBinder: trace

---

spring.profiles: test
spring.profiles.include: development

---

spring:
  profiles: production
  datasource:
    url: jdbc:${db.url}
    username: ${db.username}
    password: ${db.password}
  flyway:
    enabled: true

jpa:
  show-sql: false
  hibernate:
    ddl-auto: validate
  open-in-view: true

logging:
  level:
    org.hibernate: error

server:
  use-forward-headers: true
  error:
    whitelabel:
      enabled: false

security:
  require-ssl: true

handlebars:
  cache: true