spring:
  profiles:
    active: development

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

  devtools:
    livereload:
      enabled: true

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:~/team4-unnies;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  config: classpath:logback-${spring.profiles.active}.xml

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:~/team4-unnies;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

cloud:
  aws:
    s3:
      bucket: team4-unnies-static
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true
      accessKey: ${AWS_S3_ACCESS_KEY}
      secretKey: ${AWS_S3_SECRET_KEY}

handlebars:
  cache: false
  suffix: .html
  expose-session-attributes: true